### ISSUE TITLE
Plugwise circles

### ISSUE THREAD

**Issue by Boorkenn** [cyberjunky/home-assistant-plugwise#3]
hey, i have 24 circles in total, when i restart homeassistant it sometimes dont load some of them.
would it be possible to force it to show circles added to the config even if it cant respond at the time of loading them?

**Comment by cyberjunky** [comment]
@Boorkenn I will have a look to see if this is easy to implement.
But also have a look at below PR, it will be a much better integrated and official integration once finished I think.
https://github.com/home-assistant/core/pull/35713

**Comment by bouwew** [comment]
@Boorkenn see also this topic: https://community.home-assistant.io/t/plugwise-plugs-component/112246/58
If you don't want to wait, in this thread you can find the custom_component made by brefra.

**Comment by Boorkenn** [comment]
Alright; Thank you, i will have a look at it

**Comment by brefra** [comment]
@Boorkenn, Unfortunately, the problem you describe is also present in this integration at this time. I've already started researching whether I can make it possible to dynamically add nodes when they come online later. If possible I will add it in a future release
