### ISSUE TITLE
Timeout occured while connecting to Plugwise stick

### ISSUE THREAD

**Issue by willsmarthome** [cyberjunky/home-assistant-plugwise#4]
Afster installing I get this message:

Timeout occured while connecting to Plugwise stick
8:25:39 – plugwise (ERROR)

Setup of switch platform plugwise is taking over 10 seconds.
8:25:29 – Schakelaar (WARNING)

Config:
switch:
  - platform: plugwise
    port: /dev/ttyUSB0
    circles:
     CirclePlus: 000D6F0005692C4A
     Circle1: 000D6F000052A1AB
     Circle2: 000D6F0004B1EB31

**Comment by cyberjunky** [comment]
Check serial port config parameter for naming and write permissions for user.
Did it work before?

**Comment by willsmarthome** [comment]
This is the first time 
My ConBee2 usb-stick works OK.
These are my serial ports:
serial:
    /dev/ttyS0
    /dev/ttyUSB0
    /dev/ttyS2
    /dev/ttyS3
    /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A6010N07-if00-port0
    /dev/ttyS1
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2149155-if00
    /dev/ttyACM0

I have tried also:
/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A6010N07-if00-port0

No succes

**Comment by cyberjunky** [comment]
> I have tried also:
> /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A6010N07-if00-port0
> 
> No succes

This issue is still valid?
This is the right port.
