### ISSUE TITLE
configuration documentation

### ISSUE THREAD

**Issue by rogalian** [cyberjunky/home-assistant-plugwise#5]
Only thing in my HA set up so far, and it's giving me an error :(

2020-07-07 21:20:33 ERROR (MainThread) [homeassistant.components.switch] The plugwise platform for the switch integration does not support platform setup. Please remove it from your config.

configuration.yaml attached
[configuration.txt](https://github.com/cyberjunky/home-assistant-plugwise/files/4887139/configuration.txt)

**Comment by rogalian** [comment]
Figured it out. This line in the Manual install document should have an underscore rather than a hyphen :)

`Copy directory plugwise to your <config dir>/custom-components directory.`

**Comment by cyberjunky** [comment]
Thanks, it's corrected now!
