### ISSUE TITLE
Can't use the on/off switch in HA

### ISSUE THREAD

**Issue by Boosmoo** [cyberjunky/home-assistant-plugwise#6]
Hello Cyberjunky,

I tried your integration in HA for the Plugwise circle and circle+ but cant use the on/off switches in HA(they bounce back). I can see the power and kWh etc. What should I do?

Yours faithfully,
Boosmoo

**Comment by cyberjunky** [comment]
@Boosmoo My plugwise integration is being replaced by the Generic Plugwise component, look for "Plugwise beta custom component" in HACS. It will also be released as official integration in HA later.

**Comment by Boosmoo** [comment]
@cyberjunky is that the one from brefra?

**Comment by cyberjunky** [comment]
@boosmoo Yes that one is working here although it's beta code.

**Comment by Boosmoo** [comment]
Im using that but its still not working with the on/off switches

**Comment by Boosmoo** [comment]
@cyberjunky

**Comment by cyberjunky** [comment]
@Boosmoo I justed tested again, it works for me using brefra's code. Switching and power monitor.

**Comment by Boosmoo** [comment]
@cyberjunky did you just follow the hacs instructions?

**Comment by cyberjunky** [comment]
@boosmoo comment out all old plugwise config from your yaml, restart HA.
Install the plugwise beta integration via hacs, (restart HA, don't know if needed)
Goto integrations add Plugwise
Chooose Stick and fill in your device name ("/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A4003x7e-if00-port0" for me)

And wait a bit.
Then all sensors and switches are created.
Nothing else done here.

**Comment by Boosmoo** [comment]
@cyberjunky I did exactly that. The switches an sensors are created but when I switch it it bounces back to off again
